package com.recommendaily.client.ui.theme

import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF5455a9)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFe1e0ff)
val md_theme_light_onPrimaryContainer = Color(0xFF0c0664)
val md_theme_light_secondary = Color(0xFF5d5c71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe2e0f9)
val md_theme_light_onSecondaryContainer = Color(0xFF1a1a2c)
val md_theme_light_tertiary = Color(0xFF795369)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd7ed)
val md_theme_light_onTertiaryContainer = Color(0xFF2e1124)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbff)
val md_theme_light_onBackground = Color(0xFF1b1b1e)
val md_theme_light_surface = Color(0xFFfffbff)
val md_theme_light_onSurface = Color(0xFF1b1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe4e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF47464f)
val md_theme_light_outline = Color(0xFF787680)
val md_theme_light_inverseOnSurface = Color(0xFFf3eff4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFFc0c1ff)
//val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFc0c1ff)
val md_theme_dark_onPrimary = Color(0xFF242477)
val md_theme_dark_primaryContainer = Color(0xFF3c3d8f)
val md_theme_dark_onPrimaryContainer = Color(0xFFe1e0ff)
val md_theme_dark_secondary = Color(0xFFc6c4dc)
val md_theme_dark_onSecondary = Color(0xFF2f2f42)
val md_theme_dark_secondaryContainer = Color(0xFF454559)
val md_theme_dark_onSecondaryContainer = Color(0xFFe2e0f9)
val md_theme_dark_tertiary = Color(0xFFe9b9d3)
val md_theme_dark_onTertiary = Color(0xFF46263a)
val md_theme_dark_tertiaryContainer = Color(0xFF5f3c51)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd7ed)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1e)
val md_theme_dark_onBackground = Color(0xFFe5e1e6)
val md_theme_dark_surface = Color(0xFF1b1b1e)
val md_theme_dark_onSurface = Color(0xFFe5e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF47464f)
val md_theme_dark_onSurfaceVariant = Color(0xFFc8c5d0)
val md_theme_dark_outline = Color(0xFF918f99)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe5e1e6)
val md_theme_dark_inversePrimary = Color(0xFF5455a9)
//val md_theme_dark_shadow = Color(0xFF000000)

//val seed = Color(0xFF6768ab)
//val error = Color(0xFFba1b1b)